# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      
pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
	  - author=dependabot[bot]
      - status-success=Travis CI - Pull Request
    actions:
	  merge:
        method: merge
